version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3334:3306'
    expose:
      # Opens port 3334 on the container
      - '3334'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: